"""initial schema

Revision ID: 03c481e45fae
Revises: 
Create Date: 2026-02-10 18:30:39.937676

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03c481e45fae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('engineering', 'design', 'product', 'marketing', 'growth', 'data', 'operations', 'other', name='skillcategory'), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('primary_role', sa.Enum('engineer', 'designer', 'pm', 'marketer', 'growth', 'founder', 'other', name='userrole'), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('availability_status', sa.Enum('open_to_tribe', 'available_for_projects', 'just_browsing', name='availabilitystatus'), server_default='just_browsing', nullable=False),
    sa.Column('builder_score', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('contact_links', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('github_access_token_encrypted', sa.String(length=500), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_embedding', 'users', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_users_primary_role_availability', 'users', ['primary_role', 'availability_status'], unique=False)
    op.create_index('ix_users_search_vector', 'users', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('feed_events',
    sa.Column('event_type', sa.Enum('project_created', 'project_shipped', 'collaboration_confirmed', 'tribe_created', 'member_joined_tribe', 'builder_joined', name='eventtype'), nullable=False),
    sa.Column('actor_id', sa.String(length=26), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feed_events_actor_id', 'feed_events', ['actor_id'], unique=False)
    op.create_index('ix_feed_events_created_at_desc', 'feed_events', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('ix_feed_events_event_type_created_at', 'feed_events', ['event_type', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('owner_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('shipped', 'in_progress', 'archived', name='projectstatus'), server_default='in_progress', nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('impact_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('github_repo_full_name', sa.String(length=200), nullable=True),
    sa.Column('github_stars', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo_full_name')
    )
    op.create_index('ix_projects_embedding', 'projects', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_projects_github_repo', 'projects', ['github_repo_full_name'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index('ix_projects_search_vector', 'projects', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('tribes',
    sa.Column('owner_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'active', 'alumni', name='tribestatus'), server_default='open', nullable=False),
    sa.Column('max_members', sa.Integer(), server_default='8', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tribes_owner_id'), 'tribes', ['owner_id'], unique=False)
    op.create_index('ix_tribes_search_vector', 'tribes', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_tribes_status', 'tribes', ['status'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('skill_id', sa.String(length=26), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.create_table('project_collaborators',
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'declined', name='collaboratorstatus'), server_default='pending', nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('tribe_members',
    sa.Column('tribe_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='memberrole'), server_default='member', nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'rejected', name='memberstatus'), server_default='pending', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tribe_id', 'user_id')
    )
    op.create_table('tribe_open_roles',
    sa.Column('tribe_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('skills_needed', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('filled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('filled_by', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['filled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tribe_open_roles_tribe_id'), 'tribe_open_roles', ['tribe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tribe_open_roles_tribe_id'), table_name='tribe_open_roles')
    op.drop_table('tribe_open_roles')
    op.drop_table('tribe_members')
    op.drop_table('project_collaborators')
    op.drop_table('user_skills')
    op.drop_index('ix_tribes_status', table_name='tribes')
    op.drop_index('ix_tribes_search_vector', table_name='tribes', postgresql_using='gin')
    op.drop_index(op.f('ix_tribes_owner_id'), table_name='tribes')
    op.drop_table('tribes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_search_vector', table_name='projects', postgresql_using='gin')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index('ix_projects_github_repo', table_name='projects')
    op.drop_index('ix_projects_embedding', table_name='projects', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('projects')
    op.drop_index('ix_feed_events_event_type_created_at', table_name='feed_events')
    op.drop_index('ix_feed_events_created_at_desc', table_name='feed_events', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('ix_feed_events_actor_id', table_name='feed_events')
    op.drop_table('feed_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_search_vector', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_primary_role_availability', table_name='users')
    op.drop_index('ix_users_embedding', table_name='users', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
