"""add_build_activities_and_tribe_id

Revision ID: d88e3a3bd5d6
Revises: a1b2c3d4e5f6
Create Date: 2026-02-17 10:10:43.763350

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd88e3a3bd5d6'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_activities',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('tokens_burned', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('anthropic', 'openai', 'google', 'manual', 'other', name='buildactivitysource'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'activity_date', 'source', name='uq_build_activity_per_day')
    )
    op.create_index('ix_build_activities_project', 'build_activities', ['project_id'], unique=False, postgresql_where=sa.text('project_id IS NOT NULL'))
    op.create_index('ix_build_activities_user_date', 'build_activities', ['user_id', 'activity_date'], unique=False)
    op.add_column('projects', sa.Column('tribe_id', sa.String(length=26), nullable=True))
    op.create_foreign_key(None, 'projects', 'tribes', ['tribe_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'tribe_id')
    op.drop_index('ix_build_activities_user_date', table_name='build_activities')
    op.drop_index('ix_build_activities_project', table_name='build_activities', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_table('build_activities')
    # ### end Alembic commands ###
